site_name: Navigation SDK Documentation for Android
site_url: https://u-n-l.github.io/navigation-sdk-android-docs/
theme:
  name: material
  logo: assets/UNL logo_white.svg
  favicon: assets/Flavicon.png
  font:
    text: Poppins
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
extra_css:
  - styles/extra.css
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
nav:
  - Home: index.md
  - Overview: 01-Overview/index.md
  - Get Started: 02-Get Started/index.md
  - Core: 03-Core/index.md
  - Maps: 04-Maps/index.md
  - Positioning & Sensors: 05-Positioning & Sensors/index.md
  - Search: 06-Search/index.md
  - Routing: 07-Routing/index.md
  - Navigation: 08-Navigation/index.md
  - Offline: 09-Offline/index.md
  - Alarms: 10-Alarms/index.md
  - Weather: 11-Weather/index.md
  - Public Transit Stops: 12-Public Transit Stops.md
  - Timezone Service: 13-Timezone Service.md